#!/bin/bash
set -e

# Используем переменные окружения из .env
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Создание схемы
    CREATE SCHEMA IF NOT EXISTS $POSTGRES_SCHEMA AUTHORIZATION $POSTGRES_USER;

    -- Пользователь для приложения (ETL, dbt)
    CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $APP_DB_USER;
    GRANT USAGE ON SCHEMA $POSTGRES_SCHEMA TO $APP_DB_USER;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA $POSTGRES_SCHEMA TO $APP_DB_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $POSTGRES_SCHEMA GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $APP_DB_USER;

    -- Пользователь только для чтения (Power BI)
    CREATE USER $READONLY_USER WITH PASSWORD '$READONLY_PASSWORD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $READONLY_USER;
    GRANT USAGE ON SCHEMA $POSTGRES_SCHEMA TO $READONLY_USER;
    GRANT SELECT ON ALL TABLES IN SCHEMA $POSTGRES_SCHEMA TO $READONLY_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $POSTGRES_SCHEMA GRANT SELECT ON TABLES TO $READONLY_USER;
EOSQL