#!/bin/bash
set -e

echo "[INIT] Starting schema initialization..."

# Use environment variables passed through docker-compose
# Ensure POSTGRES_USER, APP_DB_USER, APP_DB_PASSWORD, and others
# are available in the container environment.

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOF
    -- 1. Create schemas
    CREATE SCHEMA IF NOT EXISTS ${RAW_SCHEMA} AUTHORIZATION ${POSTGRES_USER};
    CREATE SCHEMA IF NOT EXISTS ${STAGING_SCHEMA} AUTHORIZATION ${POSTGRES_USER};
    CREATE SCHEMA IF NOT EXISTS ${MARTS_SCHEMA} AUTHORIZATION ${POSTGRES_USER};

    -- 2. Configure ETL user (dbt/python)
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${APP_DB_USER}') THEN
            CREATE ROLE ${APP_DB_USER} WITH LOGIN PASSWORD '${APP_DB_PASSWORD}';
        END IF;
    END
    \$\$;

    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_DB_USER};
    GRANT CREATE ON DATABASE ${POSTGRES_DB} TO ${APP_DB_USER};
    GRANT USAGE, CREATE ON SCHEMA ${RAW_SCHEMA} TO ${APP_DB_USER};
    GRANT USAGE, CREATE ON SCHEMA ${STAGING_SCHEMA} TO ${APP_DB_USER};
    GRANT USAGE, CREATE ON SCHEMA ${MARTS_SCHEMA} TO ${APP_DB_USER};
    
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${RAW_SCHEMA} TO ${APP_DB_USER};
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${STAGING_SCHEMA} TO ${APP_DB_USER};
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${MARTS_SCHEMA} TO ${APP_DB_USER};

    -- 3. Configure BI user (read-only)
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${READONLY_USER}') THEN
            CREATE ROLE ${READONLY_USER} WITH LOGIN PASSWORD '${READONLY_PASSWORD}';
        END IF;
    END
    \$\$;

    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${READONLY_USER};
    GRANT USAGE ON SCHEMA ${MARTS_SCHEMA} TO ${READONLY_USER};
    GRANT SELECT ON ALL TABLES IN SCHEMA ${MARTS_SCHEMA} TO ${READONLY_USER};
EOF

echo "[INIT] Initialization finished successfully."