-- Создание схемы
CREATE SCHEMA IF NOT EXISTS analytics AUTHORIZATION ${POSTGRES_USER};

-- Пользователь для приложения
CREATE USER appuser WITH PASSWORD '${APPUSER_PASSWORD}';
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO appuser;
GRANT USAGE ON SCHEMA analytics TO appuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA analytics TO appuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO appuser;

-- Пользователь только для чтения (например для аналитиков или BI)
CREATE USER readonly WITH PASSWORD '${READONLY_PASSWORD}';
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO readonly;
GRANT USAGE ON SCHEMA analytics TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA analytics TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT SELECT ON TABLES TO readonly;
