version: 2

sources:
  - name: torgstat          # Имя источника для dbt (любое)
    database: torgdb        # Реальное имя базы
    schema: analytics       # Реальная схема
    tables:
      - name: users
      - name: sessions
      - name: plans
      - name: subscriptions
      - name: invoices      # Проверьте, точно ли invoices, а не orders
      - name: events